- name: Install Google Web Designer
  apt: 
    deb: https://dl.google.com/linux/direct/google-webdesigner_current_amd64.deb

- name: add apt key
  shell:
    cmd: "wget --inet4-only -qO - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/google.gpg"
