- name: Gather package facts for apt
  package_facts:
    manager: apt

- name: Remove snaps
  shell:
    cmd: snap list {{ item }} && snap remove --purge  {{ item }}
  with_items:
    - gnome-3-38-2004
    - firefox
  ignore_errors: yes
  when: '"snapd" in ansible_facts.packages'

- name: cleanup snap
  shell:
    cmd:  apt remove --purge -y snapd gnome-software-plugin-snap

- name: remove chromium-codecs-ffmpeg-extra
  apt:
    pkg: chromium-codecs-ffmpeg-extra
    state: absent

- name: get latest chromium package url
  shell: echo "http://packages.linuxmint.com/"$(wget -q -O- "http://packages.linuxmint.com/search.php?release=una&section=any&keyword=chromium" | grep "<b>chromium</b>" -A 4 |grep href |cut -d '"' -f2)
  register: chromium_url
  
- name: Print chromium URL/Version
  debug: 
    msg: "Installing chromium from: {{ chromium_url.stdout }}"
  
- name: install chrome from deb
  apt:
    deb: "{{ chromium_url.stdout }}"
