- name: Gather package facts for apt
  package_facts:
    manager: apt

- name: Remove snaps
  shell:
    cmd: snap list {{ item }} && snap remove --purge  {{ item }}
  with_items:
    - gnome-3-38-2004
    - firefox
    - snap-store
    - gtk-common-themes
    - snapd-desktop-integration
  ignore_errors: yes
  when: '"snapd" in ansible_facts.packages'

- name: cleanup snap
  shell:
    cmd:  apt remove --purge -y snapd gnome-software-plugin-snap

- name: remove chromium-codecs-ffmpeg-extra
  apt:
    pkg: chromium-codecs-ffmpeg-extra
    state: absent

- name: install chromium as deb from linux mint
  import_tasks: chromium_as_deb_from_linux_mint.yml

- name: make sure firefox is installed as .deb and not as snap
  copy:
      dest: "/etc/apt/preferences.d/99mozilla_teamppa"
      mode: '0644'
      content: |
        Package: firefox*
        Pin: release o=LP-PPA-mozillateam
        Pin-Priority: 501

        Package: firefox*
        Pin: release o=Ubuntu
        Pin-Priority: -1

- name: import apt key for mozilla team ppa
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9BDB3D89CE49EC21
    keyring: /etc/apt/trusted.gpg.d/mozillateam.gpg

- name: Add mozilla team ppa
  apt_repository:
    repo: deb https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy main
    state: present
    filename: firefox_team_ppa

- name: Make system apt update & upgrade
  import_tasks: system_update.yml

- name: remove firefox if present - will use firefox-esr
  apt:
    pkg: ['firefox']
    state: absent
    purge: yes

- name:
  apt:
    pkg: ['firefox-esr', 'firefox-esr-locale-de']
    state: present
