- name: Configure apt proxy file
  copy:
    dest: "/etc/apt/apt.conf.d/01proxy"
    content: |
       Acquire::http { Proxy "{{ apt_proxy_url }}"; };
       Acquire::https { Proxy "false"; };
    mode: "0644"
  when: apt_proxy_url is defined
