- name: use apt proxy if present
  import_tasks: set_apt_proxy.yml

- name: Update packages
  apt: update_cache=yes cache_valid_time=180

- name: Upgrade system
  apt: upgrade=full
  register: apt_result
  retries: 5
  delay: 15
  until: apt_result is success
