
- name: add an apt signing key for vscodium
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
    state: present

- name: Add vscodium repository
  apt_repository:
    repo: deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main
    state: present

- name: Update packages
  apt: update_cache=yes    

- name: Install vscodium
  apt:
    name: codium
    update_cache: yes
