
- name: make sure directory exists
  file:
    path: /home/{{ non_admin_user }}/.config/autostart
    state: directory

# if you want to execute sth. for all users, put the file into /etx/xdg/autostart
- name: Autostart file for non admin user
  copy:
    dest: "/home/{{ non_admin_user }}/.config/autostart/runAfterLogin.desktop"
    content: |
      [Desktop Entry]
      Type=Application
      Exec=/usr/local/bin/runAfterLogin.sh
      Hidden=false
      NoDisplay=false
      X-GNOME-Autostart-enabled=true
      Name[de_AT]=runAfterLogin
      Name=test
      Comment[de_AT]=Things that need to be done after login
      Comment=

- name: executable for autostart file
  copy:
    dest: "/usr/local/bin/runAfterLogin.sh"
    content: |#!/bin/bash
      sleep 3
      # clone screen
      # set default audio
    mode: 0755