- name: setup rsync
  copy:
    src: syncdata.sh
    dest: /usr/local/bin/syncdata.sh
    group: root
    owner: root
    mode: u=rwx,g=rx,o=rx

- name: create directory
  file:
    path: /data/local
    group: "{{ non_admin_user }}"
    owner: "{{ non_admin_user }}"
    state: directory

- name: Creating rsyncsecret
  copy:
    dest: "/etc/rsyncsecret"
    content: |
      {{ rsyncPassword }}
    mode: '0600'
  when: rsyncPassword is defined

- name: setup rsync
  copy:
    dest: "/usr/local/bin/syncdata.sh"
    content: |
      rsync -av --delete --password-file=/etc/rsyncsecret {{ rsyncServerURL }} /data/local
  when: rsyncServerURL is defined

- name: create directory
  file:
    path: /home/{{ non_admin_user }}/Schreibtisch
    group: "{{ non_admin_user }}"
    owner: "{{ non_admin_user }}"
    mode: '0755'
    state: directory
  when: inventory_hostname in groups["KlassenPC"]

- name: create symbolic link to sync folder
  file:
    src: "/data/local/"
    dest: "/home/{{ non_admin_user }}/Schreibtisch/unterricht"
    state: link
  when: inventory_hostname in groups["KlassenPC"]
