- name: check if google chrome or chromium-browser is installed
  ansible.builtin.package_facts:
     manager: auto

- name: Google Chrome should use simple password store ==> does not ask for keyring pwd
  ansible.builtin.replace:
    path: /usr/share/applications/google-chrome.desktop
    before: '# live site config'
    regexp: 'Exec=/usr/bin/google-chrome-stable'
    replace: 'Exec=/usr/bin/google-chrome-stable --password-store=basic'
  when: '"google-chrome-stable" in ansible_facts.packages'

- name: Chromium should use simple password store ==> does not ask for keyring pwd
  ansible.builtin.replace:
    path: /usr/share/applications/chromium-browser.desktop
    before: '# live site config'
    regexp: 'Exec=chromium-browser'
    replace: 'Exec=chromium-browser --password-store=basic'
  when: '"chromium-browser" in ansible_facts.packages'
