- name: create directory
  file:
    path: /etc/veyon/keys/public/lehrer
    state: directory

- name: copy key to clients
  copy:
    src: files/veyon_pub_key
    dest: /etc/veyon/keys/public/lehrer/key

- name: create Veyon.conf directory
  file:
    path: /etc/xdg/Veyon\ Solutions/
    state: directory

- name: copy veyon conf
  copy:
    src: files/Veyon.conf
    dest: /etc/xdg/Veyon\ Solutions/Veyon.conf

- name: create script that checks if veyon is running
  copy:
      dest: "/usr/local/bin/check_veyon.sh"
      mode: '0755'
      content: |
        #!/bin/bash
        if  veyon-cli service status |grep worker; then
            echo found
        else
          veyon-cli service restart
        fi

- name: add cronjob to check if veyon is running
  cron:
      name: check_veyon.sh
      minute: "*/2"
      job: /usr/local/bin/check_veyon.sh
